spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: realEstate
          password: realEstate
          url: jdbc:mysql://47.110.150.232:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          username: realEstate
          password: realEstate
          url: jdbc:mysql://47.110.150.232:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
      mp-enabled: true
logging:
  level:
    com.xkcoding.multi.datasource.mybatis: debug
