# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8001
  session:
    timeout:7200

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  resHost: 192.168.126.130
  storagePort: 8888  # nginx 访问端口
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  web-server-url: 192.168.126.130/
  tracker-list: 192.168.126.130:22122
