#
#nacos:
#  config:
#    server-addr: 127.0.0.1:8848
#    namespace: c8e5110d-b459-47bd-922d-25a83f276357
#server:
#  port: 6688
#keycloak:
#  realm: gravitee #当前目录所在的realm
#  resource: cool #client 名称
#  public-client: true
#  auth-server-url: http://localhost:8080/auth #keycloak启动地址
#  securityConstraints[0].authRoles[0]: user
#  securityConstraints[0].securityCollections[0].patterns: /*